import { useCallback } from 'react';
import { useLocalStorage } from './useLocalStorage';
import { STORAGE_KEYS } from '../utils/constants';
import { DEFAULT_SCHEDULE_CONFIG } from '../data/defaultScheduleConfig';
import { generateStudySchedule } from '../engine/scheduleGenerator';
import { getTodayKey } from '../utils/dateUtils';

export function useSchedule() {
  const [schedule, setSchedule] = useLocalStorage(STORAGE_KEYS.SCHEDULE, []);
  const [config, setConfig] = useLocalStorage(STORAGE_KEYS.SCHEDULE_CONFIG, DEFAULT_SCHEDULE_CONFIG);

  const generateSchedule = useCallback((tasks, subjects) => {
    const manualBlocks = schedule.filter(b => !b.isAutoGenerated);
    const newBlocks = generateStudySchedule(tasks, subjects, config, manualBlocks);
    setSchedule([...manualBlocks, ...newBlocks]);
    return newBlocks;
  }, [schedule, config, setSchedule]);

  const addBlock = useCallback((blockData) => {
    const newBlock = {
      id: crypto.randomUUID(),
      title: blockData.title || 'Study Session',
      type: blockData.type || 'study',
      subjectId: blockData.subjectId || null,
      topicId: blockData.topicId || null,
      taskId: blockData.taskId || null,
      day: blockData.day,
      startTime: blockData.startTime,
      endTime: blockData.endTime,
      isAutoGenerated: false,
      completed: false,
    };
    setSchedule(prev => [...prev, newBlock]);
    return newBlock;
  }, [setSchedule]);

  const completeBlock = useCallback((blockId) => {
    setSchedule(prev => prev.map(b => b.id === blockId ? { ...b, completed: true } : b));
  }, [setSchedule]);

  const removeBlock = useCallback((blockId) => {
    setSchedule(prev => prev.filter(b => b.id !== blockId));
  }, [setSchedule]);

  const todayBlocks = schedule
    .filter(b => b.day === getTodayKey())
    .sort((a, b) => a.startTime.localeCompare(b.startTime));

  return { schedule, setSchedule, config, setConfig, generateSchedule, addBlock, completeBlock, removeBlock, todayBlocks };
}
